<a href="https://colab.research.google.com/github/dxdoi/data-bootcamp12/blob/main/Essential_Python_for_DA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Essetial Python for DA
* object Oriented Programing
* Read and Write file
* Context Manager
* Handle Error
* Pandas & Numpy (on demand)
* Request API

In [33]:
class Dog:                                    # คล้ายๆ cookies cutter
    def __init__(self, name,species, age):    #ข้างหลัง self คือ attribute ที่เราตั้ง   -> ":"ใช้บ่งบอกว่า เป็นจุดเริ่มต้นของชุดคำสั่ง
        self.name = name
        self.species = species
        self.age = age
    def bark(self):
        print(f"{self.name} is barking 'hong hong'!")
    def hbd(self):
        self.age +=1

In [34]:
# attributes
dog1 = Dog("milo", "Chihuahua", 2)
dog2 = Dog("david", "Husky", 3)

In [35]:
dog1.name

'milo'

In [36]:
print(f"{dog1.name} is {dog1.species}")
print(f"{dog2.name} is {dog2.species}")

milo is Chihuahua
david is Husky

In [37]:
dog1.bark()
dog2.bark()

milo is barking 'hong hong'!
david is barking 'hong hong'!

In [38]:
print(dog1.age)
dog1.hbd()
print(dog1.age)

2
3

In [39]:
## homeworkd OOP for an ATM
## deposit, withdraw, check balance, OTP, order coffee, pay bill, internet etc.

In [40]:
class ATM:
    def __init__(self, ID, balance):
        self.ID = ID
        self.balance = balance

    def __str__(self):
        return f"ID: {self.ID}, Balance: {self.balance}"                   #กรณีเรา print object นี้มันสามารเรียก object นี้ขึ้นมาได้เลย
    def deposit(self, amount):
        self.balance += amount
        print(f"{self.ID}'s balance is {self.balance}")
    def withdraw(self, amount):
        self.balance -= amount
        print(f"{self.ID}'s balance is {self.balance}")
    def check_balance(self):
        print(f"{self.ID}'s balance is {self.balance}")
    def transfer(self, amount, target):
        self.balance -= amount
        target.balance += amount
        print(f"{self.ID}'s balance is {self.balance}")
        print(f"{target.ID}'s balance is {target.balance}")

In [41]:
doi = ATM("nitipat",20000)
tae = ATM("worapol",1000)
ford= ATM("piriyakorn",200000)

In [42]:
doi.check_balance()

nitipat's balance is 20000

In [43]:
doi.deposit(30000)

nitipat's balance is 50000

In [44]:
doi.check_balance()

nitipat's balance is 50000

In [45]:
doi.withdraw(5000)

nitipat's balance is 45000

In [46]:
doi.transfer(10000,tae)

nitipat's balance is 35000
worapol's balance is 11000

In [47]:
print(doi)

ID: nitipat, Balance: 35000

In [48]:
## normal class

In [49]:
class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age

In [50]:
toy = Person("toy",37)

In [51]:
toy.name

'toy'

In [52]:
#Super class/subclass

In [53]:
class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age
## extension
class Employee(Person):
    def __init__(self,name,age,company):
        super().__init__(name,age)
        self.company = company
    def greeting(self):
        print(f"Hi, my name is {self.name}")

In [54]:
Person1 = Person("toy",37)
Employee1= Employee("toy",37,"google")

In [55]:
Employee1.greeting()

Hi, my name is toy

# **Trt Except Bloc**
- เวลาโค้ดแล้วรันในไพทอน ถ้าerror Line ที่ 12 แต่โค้ดเรามี 500 บรรทัด มันจะรันไม่ได้เลยในไลนที่ 13 เป็นต้นไป
- เราเลยต้องมี try except เพื่อละบรรทัดนั้นแล้วค่อยกลับมาแก้

In [58]:
try:
    result = 1/0
except:
    print("this is as error")

this is as error

In [59]:
!ls    #"!" สามารถใช้รันคำสั่ง terminal ได้

hotel.csv  sample_data	school.csv

In [60]:
!cat hotel.csv

hotel_id,name,city,star_rating,price_per_night
101,Grand Plaza,New York,5,350
102,Ocean View,Miami,4,220
103,Mountain Retreat,Denver,4,185
104,The Urban Stay,Chicago,3,140
105,Sunset Resort,Los Angeles,5,410
106,Desert Inn,Phoenix,3,95
107,Heritage House,Boston,4,210
108,Lakeside Lodge,Seattle,3,130
109,Golden Gate Suites,San Francisco,5,380
110,Central Boutique,Austin,4,195

In [61]:
# read file
import csv

In [62]:
file = open("hotel.csv","r") # r w a (read, write, append)

#module.function()
data = csv.reader(file)
for row in data:
    print(row)
file.close()    #ต้องปิดไฟล ไม่งั้นไฟลอาจเสียหายในอนาคต

['hotel_id', 'name', 'city', 'star_rating', 'price_per_night']
['101', 'Grand Plaza', 'New York', '5', '350']
['102', 'Ocean View', 'Miami', '4', '220']
['103', 'Mountain Retreat', 'Denver', '4', '185']
['104', 'The Urban Stay', 'Chicago', '3', '140']
['105', 'Sunset Resort', 'Los Angeles', '5', '410']
['106', 'Desert Inn', 'Phoenix', '3', '95']
['107', 'Heritage House', 'Boston', '4', '210']
['108', 'Lakeside Lodge', 'Seattle', '3', '130']
['109', 'Golden Gate Suites', 'San Francisco', '5', '380']
['110', 'Central Boutique', 'Austin', '4', '195']

In [63]:
# test
try:
    file = open("Hotel.csv","r") #แกล้งใช้ H พิมใหญ่

    data = csv.reader(file)
    for row in data:
        print(row)
    file.close()
except FileNotFoundError:
    print("file not found,please check file name")
finally:
    print("read file successfully")

file not found,please check file name
read file successfully

In [64]:
# conext manager -> เปิดปิดไฟลเอง ใช้ with
read_data = []
with open("hotel.csv","r") as file:
    data = csv.reader(file)
    for row in data:
        read_data.append(row)

In [65]:
read_data

[['hotel_id', 'name', 'city', 'star_rating', 'price_per_night'],
 ['101', 'Grand Plaza', 'New York', '5', '350'],
 ['102', 'Ocean View', 'Miami', '4', '220'],
 ['103', 'Mountain Retreat', 'Denver', '4', '185'],
 ['104', 'The Urban Stay', 'Chicago', '3', '140'],
 ['105', 'Sunset Resort', 'Los Angeles', '5', '410'],
 ['106', 'Desert Inn', 'Phoenix', '3', '95'],
 ['107', 'Heritage House', 'Boston', '4', '210'],
 ['108', 'Lakeside Lodge', 'Seattle', '3', '130'],
 ['109', 'Golden Gate Suites', 'San Francisco', '5', '380'],
 ['110', 'Central Boutique', 'Austin', '4', '195']]

In [66]:
read_data[0] # ดูที่ header

['hotel_id', 'name', 'city', 'star_rating', 'price_per_night']

In [67]:
read_data[1:] #ดู body

[['101', 'Grand Plaza', 'New York', '5', '350'],
 ['102', 'Ocean View', 'Miami', '4', '220'],
 ['103', 'Mountain Retreat', 'Denver', '4', '185'],
 ['104', 'The Urban Stay', 'Chicago', '3', '140'],
 ['105', 'Sunset Resort', 'Los Angeles', '5', '410'],
 ['106', 'Desert Inn', 'Phoenix', '3', '95'],
 ['107', 'Heritage House', 'Boston', '4', '210'],
 ['108', 'Lakeside Lodge', 'Seattle', '3', '130'],
 ['109', 'Golden Gate Suites', 'San Francisco', '5', '380'],
 ['110', 'Central Boutique', 'Austin', '4', '195']]

In [68]:
# for loop to cal avg price/night
price = []

for row in read_data[1:]:
    price.append(int(row[4])) ## or -1 for last item of row
print(f"average price is {sum(price)/len(price)}")

average price is 231.5

In [69]:
# Modern pythoin
import pandas as pd
df=pd.read_csv("hotel.csv")
df.head()

   hotel_id              name         city  star_rating  price_per_night
0       101       Grand Plaza     New York            5              350
1       102        Ocean View        Miami            4              220
2       103  Mountain Retreat       Denver            4              185
3       104    The Urban Stay      Chicago            3              140
4       105     Sunset Resort  Los Angeles            5              410

In [70]:
df.price_per_night.mean()

np.float64(231.5)

# **Read & Write file**

In [2]:
import csv

In [3]:
# write file + context manager
head = ["id", "name", "city"]
body = [
    [1,"CU","BKK"],
    [2,"LSE", "London"],
    [3,"Reading","Reading"]
]
with  open("school.csv","w") as file:
    writer = csv.writer(file)
    writer.writerow(head)
    writer.writerows(body)    ## ใส่เข้าไไปหลายๆแถว

In [4]:
!ls

sample_data  school.csv

In [5]:
!cat school.csv

id,name,city
1,CU,BKK
2,LSE,London
3,Reading,Reading

In [6]:
#modern python
import pandas as pd
df = pd.read_csv("school.csv")
df.head()

   id     name     city
0   1       CU      BKK
1   2      LSE   London
2   3  Reading  Reading

In [7]:
#เปลี่ยนข้อมูลให้เป็น CSV
df.to_csv("school2.csv")

In [8]:
!ls

sample_data  school2.csv  school.csv

In [9]:
!cat school2.csv

,id,name,city
0,1,CU,BKK
1,2,LSE,London
2,3,Reading,Reading

In [10]:
## read data from internet

In [11]:
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/penguins.csv"

In [12]:
import pandas as pd
df_penguin = pd.read_csv(url)

In [13]:
df_penguin.head(10)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,MALE
6,Adelie,Torgersen,38.9,17.8,181.0,3625.0,FEMALE
7,Adelie,Torgersen,39.2,19.6,195.0,4675.0,MALE
8,Adelie,Torgersen,34.1,18.1,193.0,3475.0,NaN
9,Adelie,Torgersen,42.0,20.2,190.0,4250.0,NaN

In [14]:
df_penguin.tail()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

In [15]:
## select column
df_penguin["species"]

0      Adelie
1      Adelie
2      Adelie
3      Adelie
4      Adelie
        ...
339    Gentoo
340    Gentoo
341    Gentoo
342    Gentoo
343    Gentoo
Name: species, Length: 344, dtype: object

In [16]:
## select multiple column
df_penguin[["species","island","sex"]].head(10)

  species     island     sex
0  Adelie  Torgersen    MALE
1  Adelie  Torgersen  FEMALE
2  Adelie  Torgersen  FEMALE
3  Adelie  Torgersen     NaN
4  Adelie  Torgersen  FEMALE
5  Adelie  Torgersen    MALE
6  Adelie  Torgersen  FEMALE
7  Adelie  Torgersen    MALE
8  Adelie  Torgersen     NaN
9  Adelie  Torgersen     NaN

In [19]:
#filter row
df_penguin.query("species == 'Adelie' and island == 'Torgersen'").head(10)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,MALE
6,Adelie,Torgersen,38.9,17.8,181.0,3625.0,FEMALE
7,Adelie,Torgersen,39.2,19.6,195.0,4675.0,MALE
8,Adelie,Torgersen,34.1,18.1,193.0,3475.0,NaN
9,Adelie,Torgersen,42.0,20.2,190.0,4250.0,NaN

In [20]:
df_penguin[["species","island","sex"]].query("species == 'Adelie' and island == 'Torgersen'").head(10)

  species     island     sex
0  Adelie  Torgersen    MALE
1  Adelie  Torgersen  FEMALE
2  Adelie  Torgersen  FEMALE
3  Adelie  Torgersen     NaN
4  Adelie  Torgersen  FEMALE
5  Adelie  Torgersen    MALE
6  Adelie  Torgersen  FEMALE
7  Adelie  Torgersen    MALE
8  Adelie  Torgersen     NaN
9  Adelie  Torgersen     NaN

In [22]:
# using back slash
df_penguin[["species","island","sex"]]\
.query("species == 'Adelie' and island == 'Torgersen'")\
.head(10)

  species     island     sex
0  Adelie  Torgersen    MALE
1  Adelie  Torgersen  FEMALE
2  Adelie  Torgersen  FEMALE
3  Adelie  Torgersen     NaN
4  Adelie  Torgersen  FEMALE
5  Adelie  Torgersen    MALE
6  Adelie  Torgersen  FEMALE
7  Adelie  Torgersen    MALE
8  Adelie  Torgersen     NaN
9  Adelie  Torgersen     NaN

In [35]:
##filter without query
df_penguin[(df_penguin['species'] == "Adelie") & (df_penguin.island == "Torgersen")][["species","island","sex"]].head(10)
#ใช้ ".column" or ['column'] ก็ได้

  species     island     sex
0  Adelie  Torgersen    MALE
1  Adelie  Torgersen  FEMALE
2  Adelie  Torgersen  FEMALE
3  Adelie  Torgersen     NaN
4  Adelie  Torgersen  FEMALE
5  Adelie  Torgersen    MALE
6  Adelie  Torgersen  FEMALE
7  Adelie  Torgersen    MALE
8  Adelie  Torgersen     NaN
9  Adelie  Torgersen     NaN

# **Requests API**

In [46]:
import requests
## api endpoint
url = "https://swapi.info/api/people/1"
requests.get(url)  ## response 200 = success

In [47]:
response = requests.get(url)

In [48]:
response.json()

{'name': 'Luke Skywalker',
 'height': '172',
 'mass': '77',
 'hair_color': 'blond',
 'skin_color': 'fair',
 'eye_color': 'blue',
 'birth_year': '19BBY',
 'gender': 'male',
 'homeworld': 'https://swapi.info/api/planets/1',
 'films': ['https://swapi.info/api/films/1',
  'https://swapi.info/api/films/2',
  'https://swapi.info/api/films/3',
  'https://swapi.info/api/films/6'],
 'species': [],
 'vehicles': ['https://swapi.info/api/vehicles/14',
  'https://swapi.info/api/vehicles/30'],
 'starships': ['https://swapi.info/api/starships/12',
  'https://swapi.info/api/starships/22'],
 'created': '2014-12-09T13:50:51.644000Z',
 'edited': '2014-12-20T21:17:56.891000Z',
 'url': 'https://swapi.info/api/people/1'}

In [52]:
response.json()["name"]

'Luke Skywalker'

In [70]:
#Loop for request many charactor
import requests
import time

name=[]
for i in range (10):
    url = f"https://swapi.info/api/people/{i+1}" #เพราะ url เริ่มจากตัวเลข 1
    response = requests.get(url)         # return เป็น response object
    response_json = response.json()      # return เป็น json
    name.append(response_json["name"])
    print(f"Success : {i+1} - {name[i]}")
    time.sleep(1)

print(name)

Success : 1 - Luke Skywalker
Success : 2 - C-3PO
Success : 3 - R2-D2
Success : 4 - Darth Vader
Success : 5 - Leia Organa
Success : 6 - Owen Lars
Success : 7 - Beru Whitesun lars
Success : 8 - R5-D4
Success : 9 - Biggs Darklighter
Success : 10 - Obi-Wan Kenobi
['Luke Skywalker', 'C-3PO', 'R2-D2', 'Darth Vader', 'Leia Organa', 'Owen Lars', 'Beru Whitesun lars', 'R5-D4', 'Biggs Darklighter', 'Obi-Wan Kenobi']